[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "mariner_proj"
description = "This is the top level Arches project for the Marine HER system."
readme = {file = "README.md", content-type = "text/markdown"}
authors = []
maintainers = [{name = "Historic England", email = "donotreply@historicengland.org.uk"}]
keywords = ["arches", "extension", "django", "heritage", "historic-data", "marine-data"]
license = {text = "GNU AGPL3"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Framework :: Django",
    "Framework :: Django :: 4.2",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Information Technology",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
]
requires-python = ">=3.10"
dependencies = [
    "arches==7.6.25",
    "mariner-app @ git+https://github.com/HistoricEngland/mariner-app.git@release/1.0.2",
    "arches-he-sysref-funcs==1.0.2",
    "arches-he-data-transformation==1.0.2",
    "arches-he-location-extensions==1.0.0",
    "wfastcgi>=3.0.0,<3.1.0",
    "azure-monitor-opentelemetry>=1.0.0,<2.0.0",
    "opentelemetry-instrumentation-celery"
]
version = "1.3.0a1"

[project.optional-dependencies]
dev = [
    "livereload",
    "sst",
    "coverage",
    "django-silk==5.1.0",
    "pre-commit==3.8.0",
    "black==24.4.2",
]

[project.urls]
Homepage = "https://github.com/HistoricEngland/mariner-proj"
Repository = "https://github.com/HistoricEngland/mariner-proj.git"
Issues = "https://github.com/HistoricEngland/mariner-proj/issues"
Changelog = "https://github.com/HistoricEngland/mariner-proj/releases"
 
[tool.setuptools.packages.find]
include = ["mariner_proj*"]
exclude = ["mariner_proj.logs*"]

[tool.setuptools]
include-package-data = true