
services:
    mariner-proj-2d344:
      container_name: mariner-proj-2d344
      image: he/mariner_proj-2d344:base
      build:
        args:
          - "PROJ_NAME=mariner_proj"
          - "PROJ_REPO_NAME=mariner-proj"
          - "DOCKER_PATH=./mariner-proj/.ac_mariner_proj/docker"
        context: ../..
        dockerfile: ./mariner-proj/.ac_mariner_proj/Dockerfile
        target: base
      command: create_project
      volumes:
        - ../..:/web_root
      env_file:
        - ./docker/env_file.env
      ports:
        - 8002:8000
        - 5678:5678
      stdin_open: true
      tty: true
