
services:
    mariner-proj-2d344:
      container_name: mariner-proj-2d344
      image: he/mariner_proj-2d344:dev_build
      build:
        args:
          - "PROJ_NAME=mariner_proj"
          - "PROJ_REPO_NAME=mariner-proj"
          - "DOCKER_PATH=./mariner-proj/.ac_mariner_proj/docker"
        context: ../..
        dockerfile: ./mariner-proj/.ac_mariner_proj/Dockerfile
        target: dev
      command: run_arches
      volumes:
        - ../../arches:/web_root/arches
        - ../../mariner-proj:/web_root/mariner_proj
        #- ../../mariner_app:/web_root/mariner_app
        #- ../../arches-he-sysref-funcs:/web_root/arches_he_sysref_funcs
        #- ../../arches-he-data-transformation:/web_root/arches_he_data_transformation
        - ./docker:/web_root/docker
        - ../../mariner-proj-package:/web_root/mariner_proj_package
        - ../../mariner-proj-data:/web_root/mariner_proj_data
      env_file:
        - ./docker/env_file.env
      ports:
        - 8002:8000
        - 5678:5678
      stdin_open: true
      tty: true
    
    ## - possible 
    #mariner-proj-bash:
    #  profiles:
    #    - livereload
    #  container_name: mariner-proj-bash
    #  image: he/mariner_proj:dev_build
    #  command: ["bash"]
    #  volumes:
    #    - ../../arches:/web_root/arches
    #    - ../../mariner-proj:/web_root/mariner_proj
    #    - ./docker:/web_root/docker
    #    - ../../mariner-proj-package:/web_root/mariner_proj_package
    #    - ../../mariner-proj-data:/web_root/mariner_proj_data
    #  env_file:
    #    - ./docker/env_file.env
    #  ports:
    #    - 35729:35729      
    #  depends_on:
    #      - mariner-proj-2d344
    #  stdin_open: true
    #  tty: true

    mariner-proj-2d344-livereload:
      profiles:
        - livereload
      container_name: mariner-proj-2d344-livereload
      image: he/mariner_proj-2d344:dev_build
      command: run_livereload
      volumes:
        - ../../arches:/web_root/arches
        - ../../mariner-proj:/web_root/mariner_proj
      env_file:
        - ./docker/env_file.env
      ports:
        - 35729:35729      
      depends_on:
          - mariner-proj-2d344
      stdin_open: true
      tty: true
    
    mariner-proj-2d344-webpack:
      container_name: mariner-proj-2d344-webpack
      image: he/mariner_proj-2d344:dev_build
      command: run_webpack
      volumes:
        - ../../arches:/web_root/arches
        - ../../mariner-proj:/web_root/mariner_proj
      env_file:
        - ./docker/env_file.env
      ports:
        - 8028:8021
      depends_on:
          - mariner-proj-2d344
      stdin_open: true
      tty: true

networks:
  default:
    external: true
    name: mariner-proj-2d344-network

volumes:
    arches-log-2d344:
    arches-static-2d344:
