
services:
    nginx-mariner-proj-2d344:
      container_name: nginx-mariner-proj-2d344
      image: nginx:latest
      ports:
        - "8080:80"
      volumes:
        - ./docker/nginx-config/default.conf:/etc/nginx/conf.d/default.conf
      networks:
        - mariner-proj-2d344-network

    db-mariner-proj-2d344:
      container_name: db-mariner-proj-2d344
      image: postgis/postgis:14-3.2
      volumes:
        - ../../mariner_proj-postgres-data:/var/lib/postgresql/data
        - ../../mariner_proj-postgres-log:/var/log/postgresql
        - ./docker/init-unix.sql:/docker-entrypoint-initdb.d/init.sql # to set up the DB template
      ports:
        - '5433:5432'
      env_file: 
        - ./docker/env_file.env
      networks:
        - mariner-proj-2d344-network

    elastic-bindmount-init-mariner-proj-2d344:
      image: alpine
      container_name: elastic-bindmount-init-mariner-proj-2d344
      restart: "no"
      entrypoint: |
        /bin/sh -c "chown 1000:1000 /esBindMount"
      volumes:
        - ../../mariner_proj-elasticsearch-data:/esBindMount


    elasticsearch-mariner-proj-2d344:
      container_name: elasticsearch-mariner-proj-2d344
      image: elasticsearch:8.5.0
      volumes:
        #- ../../elasticsearch_data_mariner_proj:/usr/share/elasticsearch/data
        - ../../mariner_proj-elasticsearch-data:/usr/share/elasticsearch/data
      ports:
        - "9201:9200"
        - "9301:9300"
      env_file: 
        - ./docker/env_file.env
      networks:
        - mariner-proj-2d344-network
      depends_on:
        - elastic-bindmount-init-mariner-proj-2d344

    rabbitmq-mariner-proj-2d344:
      container_name: rabbitmq-mariner-proj-2d344
      image: rabbitmq:3.8-management
      hostname: my-rabbit
      volumes:
        - rabbitmq-data-2d344:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
        - rabbitmq-logs-2d344:/var/log/rabbitmq/log
      ports:
        - 5673:5672
        - 15673:15672
      networks:
        - mariner-proj-2d344-network

    #pg-feat-mariner-proj:
    #  container_name: pg-feat-mariner-proj
    #  image: pramsey/pg_featureserv
    #  volumes:
    #    - ../../pg_featureserv_config_mariner_proj:/config
    #  environment:
    #    - DATABASE_URL=postgresql://arches_spatial_views:arches_spatial_views@db-mariner-proj:5432/mariner_proj
    #  ports:
    #    - 9000:9000
    #  networks:
    #    - mariner-proj-network
    #  depends_on:
    #    - db-mariner-proj
    
    #pg-tile-mariner-proj:
    #  container_name: pg-tile-mariner-proj
    #  image: pramsey/pg_tileserv
    #  volumes:
    #    - ../../pg_tileserv_config_mariner_proj:/config
    #  environment:
    #    - DATABASE_URL=postgresql://arches_spatial_views:arches_spatial_views@db-mariner-proj:5432/mariner_proj
    #  ports:
    #    - 7800:7800
    #  networks:
    #    - mariner-proj-network
    #  depends_on:
    #    - db-mariner-proj


networks:
  mariner-proj-2d344-network:
    name: mariner-proj-2d344-network
    driver: bridge

volumes:
    rabbitmq-logs-2d344:
    rabbitmq-data-2d344:
