fields:
  - name: Primary Reference Number
  - name: Monument Name
    subfields:
      - Monument Name Use Type

display_descriptor_rules:
  - rule:
      - name: Primary Reference Number
        required: true
      - name: Monument Name
        field_filters:
          "Monument Name Use Type": "Primary|Statutory|Original"
        operations:
          - type: uppercase
        required: true
    format: "[{Primary Reference Number}] {Monument Name}"

  - rule:
      - name: Primary Reference Number
        required: true
      - name: Monument Name
        operations:
          - type: combine
            separator: ", "
            max_items: 3
          - type: titlecase
        required: true
    format: "[{Primary Reference Number}] {Monument Name}"

  - rule:
      - name: Primary Reference Number
        required: true
      - name: Monument Name
        default: "Unnamed Monument"
    format: "[{Primary Reference Number}] {Monument Name}"