server {

  location /featureserver/ {
    proxy_pass http://pg-feat-mariner-proj:9000/;
  }

  location /tileserver/ {
    proxy_pass http://pg-tile-mariner-proj:7800/tileserver/;
  }

  location / {
    proxy_pass http://mariner-proj:8000/;
  }

}